name: CI

on: [push]

jobs:
  test:
    name: Test on perl ${{ matrix.perl_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl_version: [ 5.22, 5.24, 5.26, 5.28 ] # xenial, stretch, bionic, buster
    container: perl:${{ matrix.perl_version }}
    steps:
    - name: Perl version
      run: perl --version
    - uses: actions/checkout@v2
    - name: Set up config
      run: |
        cp conf/general.yml-example conf/general.yml
        cp conf/council-banes_confirm.yml-example conf/council-banes_confirm.yml
        cp conf/council-buckinghamshire_confirm.yml-example conf/council-buckinghamshire_confirm.yml
        cp conf/council-hounslow_confirm.yml-example conf/council-hounslow_confirm.yml
        cp conf/council-lincolnshire_confirm.yml-example conf/council-lincolnshire_confirm.yml
        cp conf/council-northamptonshire_alloy.yml-example conf/council-northamptonshire_alloy.yml

    - name: Setup carton cache
      uses: actions/cache@v1
      with:
        path: local
        key: ${{ runner.os }}-perl-${{ matrix.perl_version }}-carton-${{ hashFiles('**/cpanfile.snapshot') }}
        restore-keys: |
          ${{ runner.os }}-perl-${{ matrix.perl_version }}-carton-

    - name: Install packages
      run: script/setup

    - name: Run tests
      if: matrix.perl_version != 5.24
      run: script/test

    - name: Run tests (with coverage)
      if: matrix.perl_version == 5.24
      run: |
        cpanm --quiet --notest Devel::Cover::Report::Codecov
        script/test
      env:
        HARNESS_PERL_SWITCHES: "-MDevel::Cover=+ignore,local/lib/perl5,^t"
    - name: Generate coverage report
      if: success() && matrix.perl_version == 5.24
      run: |
        cpanm --quiet --notest JSON::MaybeXS
        cover --report codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

